name: Upload Python Package

on:
  release:
    types: [published]

permissions:
  contents: read

jobs:
  deploy:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Install uv
      uses: astral-sh/setup-uv@v3
    - name: Set up Python
      run: uv python install
    - name: Install the project
      run: uv sync --all-extras --dev
    - name: Install tox-uv from PyPI
      uses: install-pinned/tox-uv@70c77cde128299750a16aa2c9ea8764ab543ae84  # 1.13.0
    - name: Run tests
      run: tox
    - name: Publish package
      uses: pypa/gh-action-pypi-publish@27b31702a0e7fc50959f5ad993c78deac1bdfc29
